import Head from 'next/head'
import { Player } from '@lottiefiles/react-lottie-player';
import { useEffect, useRef, useState} from 'react';

import LoopingLogo from '../assets/logo_loop_animation.json';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [logoAnimationPlayer, setLogoAnimationPlayer] = useState();
  const smoothWorkerRef = useRef();

  useEffect(() => {
    if (CSS.paintWorklet) {
      CSS.paintWorklet.addModule('https://cdn.jsdelivr.net/gh/calinoracation/onespark/worker.js');
    }
  }, []);

  useEffect(() => {
    if (!logoAnimationPlayer) return;

    function playAnimation() {
      if (!logoAnimationPlayer?.state?.instance) {
        setTimeout(playAnimation, 100);
      }

      try {
        logoAnimationPlayer.state.instance.play();
      } catch {
        setTimeout(playAnimation, 100);
      }
    }

    setTimeout(playAnimation, 300);    
  }, [logoAnimationPlayer]);

  return (
    <div className={styles.container}>
      <Head>
        <title>OneSpark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Player
          className={styles.logoAnimation}
          ref={setLogoAnimationPlayer}
          src={LoopingLogo}
          speed={2.0}
        />
        <nav>
          <ul>
            <li><a className={styles.navLink} href="/courses" style={{ animationDelay: '4100ms' }}>Courses</a></li>
            <li><a className={styles.navLink} href="/profile" style={{ animationDelay: '4250ms' }}>Current Progress</a></li>
            <li><a className={styles.navLink} href="/learn" style={{ animationDelay: '4400ms' }}>Learn</a></li>
          </ul>
        </nav>
      </main>
    </div>
  )
}