import Head from 'next/head'
import { useEffect} from 'react';

import styles from '../styles/Home.module.css'

export default function Home() {
  useEffect(() => {
    import('@lottiefiles/lottie-player');
  }, []);

  useEffect(() => {
    if (CSS.paintWorklet) {
      CSS.paintWorklet.addModule('https://cdn.jsdelivr.net/gh/calinoracation/onespark/worker.js');
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>OneSpark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logoAnimation}>
          <lottie-player
            background="#fff"
            autoplay
            loop
            src="https://assets1.lottiefiles.com/private_files/lf30_hfvmbyss.json"
          ></lottie-player>        
        </div>
      </main>
    </div>
  )
}